### ISSUE TITLE
arweave-sol is working?

### ISSUE THREAD

**Issue by wdsru** [metaplex-foundation/metaplex#1457]
I get error every time on mainnet-beta tested on several devices
```

upload was not successful, please re-run. Error: HTTP Error: Posting transaction information to the bundler: 400 "Invalid tx"
    at Function.checkAndThrow (/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/utils.js:23:19)
    at Fund.<anonymous> (/js/packages/cli/node_modules/@bundlr-network/client/build/src/fund.js:31:29)
    at Generator.next (<anonymous>)
    at fulfilled (/js/node_modules/tslib/tslib.js:114:62)
```
Can I use arweave for mainnet with many assets?

**Comment by wdsru** [comment]
Also arweave-sol works great, takes money before upload, get error  and lose sol. Withdraw does not return this.

**Comment by isodabas** [comment]
Hey i am getting similar error do you know what is the reason?

**Comment by wdsru** [comment]
I don't know

**Comment by goriunov** [comment]
Looks like bundlr has issues today. And things have been fixed now.

![image](https://user-images.githubusercontent.com/18750503/148631653-c9cd5fc5-ff21-439c-b91f-212f26b6c6e7.png)

**Comment by stegaBOB** [comment]
Looks like this issue has been fixed. Closing.

**Comment by avanti36** [comment]
Hello! Still have some problem on mainnet uploading 3 files , first time doing all this stuff)) could you helpe me?? (solana balance is ok 0.6 sol) Beginning the upload for 3 (img+json) pairs
started at: 1642674196488
config for a candy machine with publickey: ______ has been already initialized
Uploading Size 3 { mediaExt: '.png', index: '0' }
Saved bundle upload result to cache.
Computed Bundle range, including 3 file pair(s) totaling 0.065MB.
Uploading bundle via bundlr... in multiple transactions
0.000009586 SOL to upload
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data
    at Uploader.<anonymous> (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Failed bundlr upload, automatically retrying transaction in 10s (attempt: 2) Error: Not enough funds to send data
    at Uploader.<anonymous> (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)

**Comment by YosephAlves** [comment]
> Looks like this issue has been fixed. Closing.

The error is still happening...

**Comment by YosephAlves** [comment]
> Hello! Still have some problem on mainnet uploading 3 files , first time doing all this stuff)) could you helpe me?? (solana balance is ok 0.6 sol) Beginning the upload for 3 (img+json) pairs started at: 1642674196488 config for a candy machine with publickey: ______ has been already initialized Uploading Size 3 { mediaExt: '.png', index: '0' } Saved bundle upload result to cache. Computed Bundle range, including 3 file pair(s) totaling 0.065MB. Uploading bundle via bundlr... in multiple transactions 0.000009586 SOL to upload Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data at Uploader. (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23) at Generator.next () at fulfilled (/Users/a/metaplex/js/node_modules/tslib/tslib.js:114:62) at processTicksAndRejections (node:internal/process/task_queues:96:5) Failed bundlr upload, automatically retrying transaction in 10s (attempt: 2) Error: Not enough funds to send data at Uploader. (/Users/a/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/src/upload.js:221:23)

Any fixes?

**Comment by stegaBOB** [comment]
I misread the issue. Arweave is currently working, but I am unsure about arweave-sol. Will investigate now

**Comment by vijayashankar-g** [comment]
Hello, Any fix to this? I tried multiple times today (arweave-sol). 

Tried with arwwave-sol ( not working)... also is arweave working and is it recommended for mainnet ? 

below is the error. I have 1.5 sol

Failed bundlr upload, automatically retrying transaction in 10s (attempt: 1) Error: Not enough funds to send data
    at NodeUploader.dataItemUploader (/Users/kavitha/Desktop/NFT/code/Solana/metaplex/js/packages/cli/node_modules/@bundlr-network/client/build/common/upload.js:43:23)

**Comment by stegaBOB** [comment]
Bundlr/arweave-sol is a lot better now. Make sure you are on the latest version of metaplex. There is a current issue with the way we calculate the needed funding that may cause uploads to fail in certain circumstances. We are working on a fix.

**Comment by gpathela** [comment]
Hi I am still facing the issue... any update.

**Comment by sohrabious** [comment]
i am getting the same error changing the icon of my token. any update/ advice?

**Comment by sohrabious** [comment]
> Looks like this issue has been fixed. Closing.

we're still having issues!!
