### ISSUE TITLE
Unable to mint on Candy Machine UI Tutorial

### ISSUE THREAD

**Issue by rmdorsey** [metaplex-foundation/metaplex#1459]
**Describe the bug**
I've successfully compiled and started the candy machine ui application after following the steps described on the tutorial page: https://docs.metaplex.com/candy-machine-v2/mint-frontend

The UI instructs me to connect my wallet.  After connecting my wallet I see a button that says "MINT", but I'm unable to click it.  The console shows me the following errors:

<img width="557" alt="Screen Shot 2022-01-07 at 11 19 23 PM" src="https://user-images.githubusercontent.com/16293510/148632546-9845330a-f283-4d1c-9b07-fd884e842dbd.png">

I'm using the Chrome browser.

**Comment by stegaBOB** [comment]
Did you fill out your .env file correctly?

**Comment by rmdorsey** [comment]
> 

yes.

**Comment by DedaDev** [comment]
That error appears if your `goLiveDate` is `null`, unfortunately, there is no validation for the existence of the date  :/

**Comment by stegaBOB** [comment]
Thanks for bringing up this issue. We will look into it closer and hopefully get a fix out by end of weekend. Thanks again!

**Comment by ughodera** [comment]
Hi @stegaBOB,

For me the error is different, Failed to construct CandyMachineId TypeError
![Screenshot from 2022-01-08 13-22-21](https://user-images.githubusercontent.com/97296045/148636676-6974541a-8590-49ab-9efe-7dc205c5accd.png)

**Comment by PixelInvaderz** [comment]
Hi having the same issue but my goLiveDate is not null.

**Comment by rmdorsey** [comment]
updating the goLiveDate from null fixed my issue!  Thank you!  Here is what my fixed config looks like for anyone interested... 
<img width="585" alt="Screen Shot 2022-01-08 at 10 21 10 AM" src="https://user-images.githubusercontent.com/16293510/148651691-b09c4013-fda7-4ce7-ae2e-8fff5f807446.png">

**Comment by Yupiyoung** [comment]
I have this problem too, after connecting wallet, button is disabled, I have true goLiveDate, but it is not working, pls help me.

**Comment by JasonJvV** [comment]
> I have this problem too, after connecting wallet, button is disabled, I have true goLiveDate, but it is not working, pls help me.

Did you manage to solve the issue? I have the same problem. My go live date is "01 Feb 2022 00:00:00 GMT" And so should be working...

**Comment by Yupiyoung** [comment]
> > I have this problem too, after connecting wallet, button is disabled, I have true goLiveDate, but it is not working, pls help me.
> 
> Did you manage to solve the issue? I have the same problem. My go live date is "01 Feb 2022 00:00:00 GMT" And so should be working...

No, I wait answer from stegaBOB

**Comment by nancyyyy333** [comment]
Having the same issue here, try various dates for go-live date but still not working.

**Comment by dimalahbal** [comment]
same issue here , button for mint is not active 


my wallet all ready connected

**Comment by adamskrv** [comment]
Hi please i need help getting the "REACT_APP_CANDY_MACHINE_ID".. i can only see the config ID on devnet.example.

**Comment by Jjfern96** [comment]
Same issue. Mint button is not active.

**Comment by bnvds-adn** [comment]
Same issue. Unable to mint, # of collection left to mint not on display. Wallet is connected to devnet with funds, and the go live date is live set in the past.

Visual Studio code appears successful. Where else should I look to enable the mint on the devnet? Thanks! 🐸☕ gm

**Comment by Grahamrad9333** [comment]
> Same issue. Mint button is not active.

me too, please somepne help

**Comment by aidantibbitt** [comment]
@stegaBOB any fix for this?

**Comment by denboydoc** [comment]
Hi. Have same issue. Date is set
any solutions?

**Comment by janphilippfranken** [comment]
same issue, could not find a solution.

**Comment by janphilippfranken** [comment]
i get this error: 
Error: Invalid account discriminator
    at AccountClient.fetchNullable (account.ts:140:1)
    at async AccountClient.fetch (account.ts:152:1)
    at async getCandyMachineState (candy-machine.ts:176:1)
    at async Home.tsx:104:1

**Comment by stegaBOB** [comment]
It might be an anchor version issue. We're looking into it!

**Comment by janphilippfranken** [comment]
thank you!

**Comment by dangvh5** [comment]
> It might be an anchor version issue. We're looking into it!
Hi, about this "Invalid account discriminator" issues, do you have any solutions for this yet?

**Comment by the-mercenaries-ltd** [comment]
I'd like to help.

Can anybody give steps to reproduce?

To begin with, I think we'll need:
1. your current anchor version (find using `anchor -V` in terminal)
2. your local.env file (assuming your candy machine is a test one, don't share production candy machine ID before launch)
3. what commit of the metaplex repo you are using (bottom entry if you use `git log -1.` from inside ~/metaplex-foundation/metaplex [a4439e0259e2b9197cd9ef70a454c6b878df522c in the screenshot below])
4. 
<img width="729" alt="find-commit" src="https://user-images.githubusercontent.com/88769091/174458807-ca2c1d49-6431-4180-99d8-11cc9148a0d6.png">

**Comment by Egwq** [comment]
My mint button dissappears immediately you connect your wallet

**Comment by bypina** [comment]
I'm having this issue as well

node version 16.16.0
