### ISSUE TITLE
cli error loop

### ISSUE THREAD

**Issue by phong764119** [metaplex-foundation/metaplex#385]
I've got this error while uploading metadata

started at: 1631547559184
wallet public key: 5mF4pCBpNYrvMgjmZWueMbvbaAy34UVYABYZuZeT98A7
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Processing file: 0
initializing config
initialized config for a candy machine with publickey: E2H5ZuskeVxfuNamFSFeHsXp6TsLSpA8rb4447rZCHEX
Writing indices 0-0
Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]
    Program log: libstd rust_begin_panic
    Program log: panicked at 'range end index 491 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units
    Program failed to complete: BPF program panicked
    Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete
Translating error SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (D:\metaplex\js\node_modules\@solana\web3.js\lib\index.cjs.js:4863:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Connection.sendRawTransaction (D:\metaplex\js\node_modules\@solana\web3.js\lib\index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (D:\metaplex\js\node_modules\@solana\web3.js\lib\index.cjs.js:6649:21)
    at async Provider.send (D:\metaplex\js\node_modules\@project-serum\anchor\dist\cjs\provider.js:84:22)
    at async Object.rpc [as addConfigLines] (D:\metaplex\js\node_modules\@project-serum\anchor\dist\cjs\program\namespace\rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 491 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}

**Comment by AnalyticsNinja** [comment]
Same on Linux and Macos, please revert last night commit, the cli isn't working anymore

**Comment by raroman** [comment]
same, from error output this looks like the offending line? https://github.com/metaplex-foundation/metaplex/blob/master/rust/nft-candy-machine/src/lib.rs#L318

```
$  nft  cargo --version                                                                                     
cargo 1.55.0 (32da73ab1 2021-08-23)
$  nft  node --version
v16.9.0
$  nft  yarn --version
1.22.5
```
following this guide: https://hackmd.io/@levicook/HJcDneEWF

**Comment by genrative** [comment]
started at: 1631572577481
wallet public key: BGn7h1Xa3KcsJfqwFGYMkSQJUaxEi7X6N3EjpGwR2aa
program id from anchor cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ
Processing file: 0
(node:42670) UnhandledPromiseRejectionWarning: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Object.<anonymous> (/snapshot/js/packages/cli/build/commands/upload.js:149:37)
    at step (/snapshot/js/packages/cli/build/commands/upload.js:63:23)
    at Object.next (/snapshot/js/packages/cli/build/commands/upload.js:44:53)
    at fulfilled (/snapshot/js/packages/cli/build/commands/upload.js:35:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `metaplex --trace-warnings ...` to show where the warning was created)
(node:42670) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:42670) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will

**Comment by AnalyticsNinja** [comment]
Fixed here #389

**Comment by daiyis** [comment]
> Fixed here #389

still the same error after pull the latest master with the fix.

saving config line 0-1 failed SendTransactionError: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: Program failed to complete
    at Connection.sendEncodedTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4863:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Connection.sendRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:4822:20)
    at async Object.sendAndConfirmRawTransaction (/snapshot/js/node_modules/@solana/web3.js/lib/index.cjs.js:6649:21)
    at async Provider.send (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/provider.js:84:22)
    at async Object.rpc [as addConfigLines] (/snapshot/js/node_modules/@project-serum/anchor/dist/cjs/program/namespace/rpc.js:11:31) {
  logs: [
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ invoke [1]',
    'Program log: libstd rust_begin_panic',
    "Program log: panicked at 'range end index 731 out of range for slice of length 255', nft-candy-machine/src/lib.rs:318:18",
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ consumed 200000 of 200000 compute units',
    'Program failed to complete: BPF program panicked',
    'Program cndyAnrLdpjq1Ssp1z8xxDsB8dxe7u4HL5Nxi2K5WXZ failed: Program failed to complete'
  ]
}

**Comment by fatihhkuru** [comment]
Did anyone solve this problem?

**Comment by alvaroartano** [comment]
i have the same problem, anyone managed to solve it?

**Comment by mvelebit** [comment]
```The first item in your collection must have the index 0, the second 1 and so forth.``` as is reads in the [docs](https://docs.metaplex.com/candy-machine-v2/preparing-assets)
