### ISSUE TITLE
yarn build wont execute in cd js

### ISSUE THREAD

**Issue by scotig33** [metaplex-foundation/metaplex#829]
**Describe the bug**

**To Reproduce**
1. Go to '.yarn run v1.22.17
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 4 packages: "yarn run build"
lerna ERR! yarn run build exited 1 in '@oyster/common'
lerna ERR! yarn run build stdout:
$ run-s build-ts build-css
$ tsc
src/utils/index.tsx(13,15): error TS2307: Cannot find module './assets' or its corresponding type declarations.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.      
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.      

lerna ERR! yarn run build stderr:
error Command failed with exit code 2.
ERROR: "build-ts" exited with 2.
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in '@oyster/common'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.    
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command. ..'

**Comment by kuzudoli** [comment]
Follow this steps, it maybe can help you:

> git clone https://github.com/carthanas/metaplex.git
> cd metaplex
> git checkout bf1bc27098ab9a8b5fda4feef2209f5ccfbc8207 -- js/yarn.lock
> cd js
> yarn install
> yarn bootstrap
> yarn build

**Comment by carthanas** [comment]
This was fixed in PR https://github.com/metaplex-foundation/metaplex/pull/849

Pull the latest from master and you should be good 👍

**Comment by chahakshah111** [comment]
Hey @carthanas i'm still getting that error while running yarn build.

**Comment by chahakshah111** [comment]
i don't know why but on the first 2 attempt I got this error 
lerna ERR! yarn run build stderr:
Failed to compile.

./src/actions/addTokensToVault.ts:9:8
Type error: Cannot find module '@oyster/common' or its corresponding type declarations.

   7 |   toPublicKey,
   8 |   WalletSigner,
>  9 | } from '@oyster/common';
     |        ^
  10 | import { SafetyDepositConfig } from '@oyster/common/dist/lib/models/metaplex/index';
  11 | import { approve } from '@oyster/common/dist/lib/models/account';
  12 | import { createTokenAccount } from '@oyster/common/dist/lib/actions/account';
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

but after that It build successfully.

**Comment by chahakshah111** [comment]
i don't know why but in first 2 attempt i was getting this error 
`lerna ERR! yarn run build stderr:
Failed to compile.

./src/actions/addTokensToVault.ts:9:8
Type error: Cannot find module '@oyster/common' or its corresponding type declarations.

   7 |   toPublicKey,
   8 |   WalletSigner,
>  9 | } from '@oyster/common';
     |        ^
  10 | import { SafetyDepositConfig } from '@oyster/common/dist/lib/models/metaplex/index';
  11 | import { approve } from '@oyster/common/dist/lib/models/account';
  12 | import { createTokenAccount } from '@oyster/common/dist/lib/actions/account';
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 1 child process to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

But after that it build successfully.

**Comment by carthanas** [comment]
Glad it resolved itself! Just make sure you're up to date with master, clean your node_modules and go again.

**Comment by jonathanolsen** [comment]
Still have this same issue with the latest version

**Comment by jclmnop** [comment]
> Still have this same issue with the latest version

Same 

`yarn run v1.22.15
$ lerna run build
lerna notice cli v3.22.1
lerna info versioning independent
lerna info Executing command in 5 packages: "yarn run build"
lerna info run Ran npm script 'build' in '@oyster/common' in 13.8s:
$ run-s build-ts build-css
$ tsc
$ less-watch-compiler src/ dist/lib/ --run-once
Running less-watch-compiler once.
lerna info run Ran npm script 'build' in '@metaplex/cli' in 22.1s:
$ tsc -p ./src
lerna ERR! yarn run build exited 1 in 'web'
lerna ERR! yarn run build stdout:
$ next build
info  - Loaded env from /Users/jclmnop/programming/rust/solana/sendHelp/metaplex/js/packages/web/.env.production
info  - Loaded env from /Users/jclmnop/programming/rust/solana/sendHelp/metaplex/js/packages/web/.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types...
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

lerna ERR! yarn run build stderr:
Failed to compile.

./src/views/packCreate/components/Header/data.ts:17:20
Type error: Property 'DesignAndInfo' does not exist on type 'typeof CreatePackSteps'.

  15 |   //   title: 'Pricing & Expiration ',
  16 |   // },
> 17 |   [CreatePackSteps.DesignAndInfo]: {
     |                    ^
  18 |     title: 'Design your pack',
  19 |   },
  20 |   [CreatePackSteps.ReviewAndMint]: {
error Command failed with exit code 1.

lerna ERR! yarn run build exited 1 in 'web'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.`

**Comment by yasielken** [comment]
@jclmnop Gives error because there are commented lines of code. This was my solution:

**Step 1:**
_Locate the following line of code that is in this path:_"**js/packages/web/src/views/packCreate/types.ts**"_
export enum CreatePackSteps {
  SelectItems,
  SelectVoucher,
  AdjustQuantities,
  // SalesSettings, **<-Removes comment**
  // DesignAndInfo,**<-Removes comment**
  ReviewAndMint,
}

**Step 2:**
_Then remove the comments to these lines of code from the following file:_"**js/packages/web/src/views/packCreate/componets/Sidebar/data.ts**"

import { CreatePackSteps } from '../../types';

export const STEPS_TITLES: Record<CreatePackSteps, string> = {
  [CreatePackSteps.SelectItems]: 'Select Items',
  [CreatePackSteps.SelectVoucher]: 'Select Voucher',
  [CreatePackSteps.AdjustQuantities]: 'Adjust Quantities',
  [CreatePackSteps.SalesSettings]: 'Sales Settings',
  [CreatePackSteps.DesignAndInfo]: 'Info & Design',
  [CreatePackSteps.ReviewAndMint]: 'Review & Mint',
};

export const CONTINUE_TITLES: Record<CreatePackSteps, string> = {
  [CreatePackSteps.SelectItems]: 'Continue to Voucher',
  [CreatePackSteps.SelectVoucher]: 'Continue to Quantities',
  [CreatePackSteps.AdjustQuantities]: 'Continue to Mint',
  // [CreatePackSteps.SalesSettings]: 'Continue to Design',**<-Removes comment**
  // [CreatePackSteps.DesignAndInfo]: 'Continue to Mint',**<-Removes comment**
  [CreatePackSteps.ReviewAndMint]: 'Confirm & Mint',
};

And all ready

**Comment by jclmnop** [comment]
@yasielken 

This almost solved my problem, just had to do the same thing in `packages/web/src/views/packCreate/components/Header/data.ts` as well.

Thanks man.

**Comment by jonathanolsen** [comment]
Worked! Thanks!
